version: '3.7'
services:

  php-fpm:
    image: ${DOCKER_REGISTRY}/${DOCKER_PHP_APP_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    container_name: ${DOCKER_PROJECT}-php-fpm
    environment:
      ENV: ${ENV}
      DOCKER_PROJECT: ${DOCKER_PROJECT}
      RENDER_MODE: ${RENDER_MODE}
      API_AUTH_KEY: ${API_AUTH_KEY}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PHINX_DB_HOST: ${DB_HOST}
      PHINX_DB_PORT: ${DB_PORT}
      PHINX_DB_NAME: ${DB_NAME}
      PHINX_DB_USER: ${DB_USER}
      PHINX_DB_PASSWORD: ${DB_PASSWORD}
      DEBUG: ${DEBUG}
    depends_on:
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  nginx:
    image: ${DOCKER_REGISTRY}/${DOCKER_NGINX_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    container_name: ${DOCKER_PROJECT}-nginx
    ports:
      - ${APP_WEB_PORT}:80
    environment:
      PHP_UPSTREAM_CONTAINER: ${PHP_UPSTREAM_CONTAINER}
      PHP_UPSTREAM_PORT: ${PHP_UPSTREAM_PORT}
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  swagger:
    image: ${DOCKER_REGISTRY}/${DOCKER_SWAGGER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}
    restart: always
    container_name: ${DOCKER_PROJECT}-swagger
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"

volumes:
  mysql: